name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:rrrr)

variables:
  - group: Docker Bios
  - name: buildConfiguration
    value: "Release"
  # Helm
  - name: chartPath
    value: deploy/charts # Path to Helm charts directory
  - name: chartName
    value: # Pattern: bios-{service-name}, e.g., bios-agents-asset-harmonizer
  # Service
  - name: projectLocation
    value: .
  - name: containerName
    value: bechtle-ios/bios-agents-asset-harmonizer # Pattern: bechtle-ios/bios-{service-name}, e.g., bechtle-ios/bios-agents-asset-harmonizer
  - name: projectFile
    value: pyproject.toml
  # Versioning
  - name: versionFilePath
    value: ${{variables.projectLocation}}/${{variables.projectFile}}

trigger:
  branches:
    include:
      - master
      - main
      - release/*
      - develop
  tags:
    include:
      - v*
  paths:
    exclude:
      - azure-pipelines.yml

resources:
  repositories:
    - repository: templates
      type: git
      name: PipelineTemplates

stages:
  - stage: Build
    jobs:
      - job: Docker
        pool: "Docker"
        steps:
          - checkout: self
            submodules: true
            persistCredentials: true
            clean: true

          - template: extract-version-info.yml@templates
            parameters:
              versionFilePath: ${{variables.versionFilePath}}

          # build Service
          - template: build-project-container.yml@templates
            parameters:
              projectLocation: "$(Build.SourcesDirectory)/$(projectLocation)"
              projectFile: $(projectFile)
              buildContext: $(Build.SourcesDirectory)
              containerName: $(containerName)

          # build Helm
          # - template: build-helm-chart.yml@templates
          #   parameters:
          #     chartBasePath: $(chartPath)
          #     chartName: $(chartName)
