# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)_$(Rev:rrrr)

variables:
  - group: Docker Bios
  - name: buildConfiguration
    value: 'Release'
  # Helm
  - name: chartPath
    value: deploy/charts
  - name: chartName
    value: bios-harmonizing-agent
  # Service
  - name: projectLocation
    value: .
  - name: containerName
    value: bios-harmonizing-agent
  - name: versionFilePath
    value: custom/pyproject.toml

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - azure-pipelines.yml

resources:
  repositories:
    - repository: templates
      type: git
      name: PipelineTemplates

stages:
  - stage: Build
    jobs:
      - job: Docker
        pool: 'Docker'
        steps:
          - template: extract-version-info.yml@templates
            parameters:
              versionFilePath: ${{ variables.versionFilePath }}

            # build Service
          - template: build-project-container.yaml@templates
            parameters:
              projectLocation: '$(Build.SourcesDirectory)/$(projectLocation)'
              containerName: '$(containerRepo)/$(containerName)'

          #   # build Helm
          # - template: build-helm-chart.yaml@templates
          #   parameters:
          #     versionFilePath: '$(Build.SourcesDirectory)/$(projectLocation)/$(projectFile)'
          #     chartBasePath: $(chartPath)
          #     chartName: $(chartName)
