version: "3.8"

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DYNACONF_APP_NAME=agents-item-harmonizer
      - DYNACONF_LOG_LEVEL=INFO
      - DYNACONF_LOG_FORMAT=json
      - DYNACONF_APP_PORT=8000
      - DYNACONF_PROMPT_SEARCH_PATHS=/home/app/custom/src/prompts
      - DYNACONF_AI_MODEL_PROVIDER=vllm
      - DYNACONF_AI_MODEL_NAME=default
      - DYNACONF_AI_MODEL_BASE_URL="https://avs-vllm.q14.net/v1"
      - DYNACONF_AI_MODEL_API_KEY="put-your-api-key-here"
      - DYNACONF_OTEL_ENDPOINT=http://jaeger:14268/api/traces
      - DYNACONF_OTEL_SERVICE_NAME=agents-item-harmonizer
      - DYNACONF_DAPR_HTTP_PORT=3500
      - DYNACONF_DAPR_GRPC_PORT=50001
      - DYNACONF_EVENT_PUBLISHING__DEFAULT_PUBSUB_NAME="rabbitmq-pubsub"
      - DYNACONF_EVENT_PUBLISHING__TOPIC_MAPPING__asset-harmonized-v1=dev.asset.harmonized.v1
      - DYNACONF_SUPPORTED_EVENTS=asset-score-v1
    depends_on:
      - jaeger
      - redis
      - rabbitmq
    volumes:
      - ./custom/src/prompts:/home/app/custom/src/prompts:ro
    networks:
      - agent-network

  agent-dapr:
    image: "daprio/daprd:latest"
    command:
      [
        "./daprd",
        "-app-id",
        "agents-item-harmonizer",
        "-app-port",
        "8000",
        "-dapr-http-port",
        "3500",
        "-dapr-grpc-port",
        "50001",
        "-placement-host-address",
        "placement:50006",
        "-components-path",
        "/components",
        "-config",
        "/config/config.yaml",
      ]
    volumes:
      - "./dapr/components:/components"
      - "./dapr/config:/config"
    depends_on:
      - agent
      - redis
      - rabbitmq
      - placement
    network_mode: "service:agent"

  placement:
    image: "daprio/dapr:latest"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - agent-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - agent-network

  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - agent-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - agent-network

networks:
  agent-network:
    driver: bridge
