[pytest]
minversion = 7.0
addopts = -ra -q --strict-markers --ignore=docs/trials
testpaths = tests examples
asyncio_mode = auto
pythonpath = src:examples/trivia_game:examples/rest_microservice:examples/simple_event_processor:examples/complex_agent
