apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rabbitmq-secret
spec:
  type: secretstores.local.env
  version: v1
  metadata:
  - name: multiValued
    value: "true"
scopes:
- asset-backup-checker
