"""Request and response schemas for the customer support Q&A collaboration."""

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class ValidationStatus(str, Enum):
    """Status of answer validation."""

    APPROVED = "approved"
    REJECTED = "rejected"
    NEEDS_REVISION = "needs_revision"


class SupportRequest(BaseModel):
    """Request for customer support answer."""

    question: str = Field(..., description="Customer's question")
    category: str = Field(default="general", description="Question category: technical, billing, general, product")
    context: str = Field(default="", description="Additional context about the customer or situation")


class SupportAnswer(BaseModel):
    """Answer generated by junior support agent."""

    session_id: str = Field(..., description="Session ID")
    answer: str = Field(..., description="Detailed answer to the question")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence level (0-1)")
    sources: list[str] = Field(default_factory=list, description="Referenced knowledge sources")


class ValidationResult(BaseModel):
    """Validation result from senior agent."""

    session_id: str = Field(..., description="Session ID")
    status: ValidationStatus = Field(..., description="Validation status")
    reason: str = Field(..., description="Brief reason for approval/rejection")


class SupportSession(BaseModel):
    """Complete support session data."""

    session_id: str = Field(..., description="Unique session identifier")
    question: str = Field(..., description="Original question")
    category: str = Field(..., description="Question category")
    junior_answer: Optional[SupportAnswer] = Field(None, description="Junior's answer")
    senior_validation: Optional[ValidationResult] = Field(None, description="Senior's validation")


class SupportResponse(BaseModel):
    """Response containing the complete Q&A interaction."""

    session_id: str = Field(..., description="Session ID")
    question: str = Field(..., description="Original question")
    answer: str = Field(..., description="Answer from junior agent")
    confidence: float = Field(..., description="Confidence level")
    sources: list[str] = Field(..., description="Referenced sources")
    validated: bool = Field(..., description="Whether answer was approved by senior")
    validation_reason: str = Field(..., description="Senior's validation reason")
    status: ValidationStatus = Field(..., description="Validation status")
