apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "http://localhost:4317"
  logging:
    appLogDestination: "console"
    appLogLevel: "info"
  metric:
    enabled: true
  api:
    allowed:
      - name: "state"
        version: "v1"
        protocol: "http"
      - name: "pubsub"
        version: "v1" 
        protocol: "http"
  middleware:
    http:
      - name: "uppercase"
        type: "middleware.http.uppercase"
  accessControl:
    defaultAction: "allow"
    trustDomain: "public"
    policies:
    - appId: "asset-backup-checker"
      defaultAction: "allow"
      trustDomain: "public"
      namespace: "default"
