apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: asset-events-subscription
spec:
  topic: assets.metadata
  routes:
    default: /events/assets
  pubsubname: rabbitmq-pubsub
  metadata:
    rawPayload: "false"
    ackWaitTime: "600s"
    maxInFlight: "25"
    autoAck: "false"
  deadLetterTopic: assets.metadata.dlq
scopes:
- asset-backup-checker
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: asset-created-subscription
spec:
  topic: assets.created
  routes:
    default: /events/assets
  pubsubname: rabbitmq-pubsub
  metadata:
    rawPayload: "false"
    ackWaitTime: "600s"
    maxInFlight: "25"
    autoAck: "false"
  deadLetterTopic: assets.created.dlq
scopes:
- asset-backup-checker
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: backup-config-changed-subscription
spec:
  topic: assets.backup.config.changed
  routes:
    default: /events/assets
  pubsubname: rabbitmq-pubsub
  metadata:
    rawPayload: "false"
    ackWaitTime: "600s"
    maxInFlight: "25"
    autoAck: "false"
  deadLetterTopic: assets.backup.config.changed.dlq
scopes:
- asset-backup-checker
---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: backup-check-requested-subscription
spec:
  topic: assets.backup.check.requested
  routes:
    default: /events/assets
  pubsubname: rabbitmq-pubsub
  metadata:
    rawPayload: "false"
    ackWaitTime: "600s"
    maxInFlight: "25"
    autoAck: "false"
  deadLetterTopic: assets.backup.check.requested.dlq
scopes:
- asset-backup-checker
